version: "3"

services:
  zookeeper:
    container_name: "go-kafka-zookeeper"
    image: "bitnami/zookeeper:latest"
    networks:
      - go-kafka
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: "go-kafka-server"
    image: "bitnami/kafka:latest"
    networks:
      - go-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.99.100:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

networks:
  go-kafka:
    driver: bridge
